spring.application.name=spring-boot-final-project

# Активация dev профиля
spring.config.activate.on-profile=dev

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

springdoc.api-docs.info.title=My Application API
springdoc.api-docs.info.description=API
springdoc.api-docs.info.version=1.0.0
springdoc.api-docs.info.contact.name=Developer
springdoc.api-docs.info.contact.email=dev@example.com

# Настройки логирования:
logging.config=classpath:logback-spring.xml
# Кастомные настройки логирования для аспекта
custom.logging.enabled=true
custom.logging.level=DEBUG

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/myapp
spring.datasource.username=root
spring.datasource.password=ENC(9vAbVyJKNNwfUWgs/6jsqw==)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Для корректной работы Lombok с MapStruct
spring.main.allow-bean-definition-overriding=true

# В application-dev.properties
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Ключ для шифрования (можно передавать через переменные окружения)
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:master-key}
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

# JWT Configuration(длина не менее 32 символов)
jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsAtLeast32BytesLongForHS256Algorithm}
# 24 часа в секундах
jwt.expiration=86400  

#Spring Boot Actuator
management.endpoints.web.exposure.include=*
# Micrometer
management.metrics.tags.application=${spring.application.name}