USE
myapp;

DELETE
FROM USERS;

INSERT INTO USERS
    (ID, DISPLAY_NAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, STARTPOINT)
VALUES(1,'admin','admin@gmail.com','admin','admin','admin',CURRENT_TIMESTAMP)